### ISSUE TITLE
zas is too complex

### ISSUE THREAD

**Issue by luckypoem** [imdario/zas#10]
can u publish a demo blog's source code based on zas?

**Comment by imdario** [comment]
Yes, sure. I will try to do it during the next month. Thanks for your suggestion.

**Comment by luckypoem** [comment]
hello.

now is april.can u take some time to publish a demo blog's source code based on zas?

**Comment by luckypoem** [comment]
and could u see here: https://github.com/zserge/zserge.github.io/issues/4 ,how can i make the  published post to appear in the homepage?

tks

**Comment by imdario** [comment]
By "next month" I meant  the next four weeks (two left). Zas doesn't have direct blogging support, but I can be implemented through plugins: https://github.com/imdario/zas#configuration-and-extension

Also, you can find a website example here: https://github.com/imdario/lyd

**Comment by luckypoem** [comment]
hello.
 
as per https://github.com/imdario/lyd ,i also setup a site: http://gcv.bright.biz.st:23186 ,but 2 published posts also don't appear in the homepage: 
http://gcv.bright.biz.st:23186/test-1.html and http://gcv.bright.biz.st:23186/test-2.html 

how to make the published posts to appear in the homepage?

tks

**Comment by imdario** [comment]
Zas doesn't automagically generate anything. It is completely unaware of your posts because it doesn't assume a fixed structure.

If you want a nice static generator with blog support, please use Hugo: https://gohugo.io/
