### ISSUE TITLE
blackfriday?

### ISSUE THREAD

**Issue by rbucker** [imdario/zas#13]
```
$ go get github.com/imdario/zas
package github.com/russross/blackfriday/v2: cannot find package "github.com/russross/blackfriday/v2" in any of:
        /usr/local/go/src/github.com/russross/blackfriday/v2 (from $GOROOT)
        /home/xyz/go/src/github.com/russross/blackfriday/v2 (from $GOPATH)
```

now I know why hugo?

**Comment by imdario** [comment]
The issue is from blackfriday/v2. It doesn't work well if it's not under "go mod". Check this:

```
$ git clone https://github.com/imdario/zas
$ go get -u -v
$ go install ./...
$ mkdir /tmp/testsite && cd /tmp/testsite
$ zas init
Initialized empty Zas repository in /tmp/testsite/.zas
```

This "issue" appeared long after Hugo's success. So, Zas' success (or lack of it) is unrelated to this.

**Comment by rbucker** [comment]
cool, thanks. While this works it sortof takes away from the SIMPLE simple in the README. I was sold on the contents of a single ```go get``` with a simple DEP chain.
